Hotfix/unbag2
RoboEagles4828/2018Robot pull request #28
Opened 2018-03-25 01:57 UTC by jacksondm33

Merge competition code into master

2018-03-25 01:57 UTC, jacksondm33 commented
This should be merged after competition.

2018-03-27 19:53 UTC, CheezBallzPi submitted a review, later dismissed

2018-03-27 19:55 UTC, CheezBallzPi requested changes
Are you sure these brakes are unnecessary? They were needed for auton to work in the past.

2018-03-27 22:18 UTC, jacksondm33 commented
They weren't necessary unless it timed out. I just fixed that.

2018-03-30 21:17 UTC, CheezBallzPi approved these changes

2018-03-30 21:17 UTC, merged